### ISSUE TITLE
Add native support for UUID data type

### ISSUE THREAD

**Issue by MohammedBajuaifer** [microsoft/mssql-django#134]
I keep getting this error **[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting from a character string to uniqueidentifier.**

And the problem is because mssql-django does not use uniqueidentifier as the data type for UUIDFields,

I change the _has_native_uuid_field_  to True and it's working. Also created a PR #135 

Is there any reason to why this is not support by default?

**Comment by jmah8** [comment]
The reason this is not supported by default is because mssql-django uses **char(32)** not **uniqueidentifier** as the **UUIDField** which can be seen in
https://github.com/microsoft/mssql-django/blob/5823873bf207637cb6cd2eb22975e189e49fad0a/mssql/base.py#L118

By just changing the _has_native_uuid_field_ to True it causes some unit test to fail, which is why PR #135 is failing the pipeline.

**Comment by MohammedBajuaifer** [comment]
Hello @jmah8, thanks for clarifying. Is there way to overrwrite it?

**Comment by XF-FW** [comment]
Any interest here?

My use-case, is that django is not the only application touching the database and it's not handling the migrations at all (however they're used in testing and development). My workaround is to use a charfield, which is less than satisfying.

Tagging #40, since it's related to this.

**Comment by ryancheley** [comment]
I have a similar situation to @XF-FW and would really like to see native support for UUID.

**Comment by DrMeosch** [comment]
It would be really nice to have it implemented. Are there any plans, guys?

**Comment by dauinsight** [comment]
Hi @DrMeosch , we will be reinvestigating the scope of work here and update you on our findings. Thank you

**Comment by dauinsight** [comment]
We're planning to have native support for UUID's in the next release. Thanks everyone for chiming in

**Comment by nils-van-zuijlen** [comment]
These changes were reverted because of #363. Could you reopen the issue?

**Comment by cpowr** [comment]
Had the same issue. Is there a solution in the works that accommodates both #329 and #363?
