### ISSUE TITLE
Unable to install with Django >4.0

### ISSUE THREAD

**Issue by ablackshear** [microsoft/mssql-django#315]
I am trying to install mssql-django 1.3 alongside Django 4.2, but conda wants to force a downgrade to Django. Starting with a new environment, solving the environment fails with this message 

Could not solve for environment specs
The following packages are incompatible
├─ django 4.2.7**  is requested and can be installed;
└─ mssql-django 1.3**  is uninstallable because it requires
   └─ django >=2.2,<4.1 , which conflicts with any installable versions previously reported.

**Comment by mShan0** [comment]
Apologies if I get anything wrong since I'm unfamiliar with Conda (and we're not the ones uploading it to this platform), but it seems like Conda itself has the dependency requirement incorrect at first glance. Mssql-django 1.3 supports 4.2. Is there any way you can install mssql-django via PyPI?

![image](https://github.com/microsoft/mssql-django/assets/96149598/12c7b92a-2399-48a4-ae02-b6995653d15a)

**Comment by ablackshear** [comment]
Oh I see, I didn't realize it was conda and not mssql-django adding that dependency requirement. Our environment already has a few things that need to be pip-installed rather than from conda, I just added mssql-django to that list and it installed successfully alongside Django 4.2.7. Thanks!
