### ISSUE TITLE
string to uniqueidentifier conversion exception

### ISSUE THREAD

**Issue by Starman1984** [microsoft/mssql-django#40]
I have a table that uses an uniqueidentifier when adding a new record via admin page a uniqueidentifier conversion exception 
is returned. Tried overriding .Save but with no luck, do you have any thoughts? 

The table is as follows:
    CREATE TABLE [dbo].[DictionaryEntries](
        [EntryGUID] [uniqueidentifier] NOT NULL,
        [Description] [varchar](50) NOT NULL,
    CONSTRAINT [pkEntry] PRIMARY KEY CLUSTERED 
    (
        [EntryGUID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO

    ALTER TABLE [dbo].[DictionaryEntries] ADD  DEFAULT (newid()) FOR [EntryGUID]
    GO

The Exception Message is as follows:
ProgrammingError at /admin/DictionaryApp/dictionaryentries/add/
('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Conversion failed when converting from a character string to uniqueidentifier. (8169) (SQLExecDirectW)')
Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin/DictionaryApp/dictionaryentries/add/
Django Version:	3.1
Exception Type:	ProgrammingError
Exception Value:	
('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]Conversion failed when converting from a character string to uniqueidentifier. (8169) (SQLExecDirectW)')
Exception Location:	D:\python\code\dictionary\.env\lib\site-packages\mssql\base.py, line 561, in execute
Python Executable:	D:\python\code\dictionary\.env\Scripts\python.exe
Python Version:	3.9.1

Model as follows:
    from django.db import models
    from uuid import UUID, uuid4
    import uuid

class DictionaryEntries(models.Model):
    EntryGUID   = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    Description = models.CharField(db_column='Description', unique=True, max_length=50)  

    class Meta:
        managed = False
        db_table = 'DictionaryEntries'
        ordering = ['Description']
        verbose_name = "Dictionary Entries"
        verbose_name_plural = "Dictionary Entries"

what i tried:
    override save in an attempt at manual conversion 

    def save(self, *args, **kwargs):
        self.EntryGUID = uuid(self.EntryGUID)
        super(DictionaryEntries, self).save(*args, **kwargs)

**Comment by aceofwings** [comment]
UUID fields are an interesting topic that I tried covering several years ago. Currently the project has no support for native UUID and will use Char(32) or Char(36)... Can not remember exactly. Some older ODBC drivers will omit "-" characters depending on the version of sqlserver you are running. Now... I recommend trying several things

1. UUID fields to be Char(32) or Char(36) fields in your schema
2. Remove default newid() as django will take care of the insertion and generation. 

Note : The way django handles the joins of UUIDs is fairly poor and will throw errors


Now what can we do to reach the point of native UUID?

1. Enable the Flag Native UUID in features.py
2. Fix Migrations as the UUID function is interpreted as a callable and therefore will result in a alter statement with a default being an actual UUID value instead of newid()

And I think that's it.
