### ISSUE TITLE
Support altering from/to (Big)AutoField

### ISSUE THREAD

**Issue by marciobbj** [microsoft/mssql-django#55]
Hello.

I have been trying to migrate some of my tables, from `<django.db.models.fields.IntegerField: id>` to a `<django.db.models.fields.BigAutoField: id>`. 

This change seems not to be supported by this backend since I am getting a ```NotImplementedError: the backend doesn't support altering from/to AutoField.``` . I would like to know if there is some way to make this work since I am trying to avoid scaling problems when my DB starts to increase.

I would be glad to work on this change too if necessary, I just need a little more context on why this is not supported yet and the problems I would be probably facing.

Thanks.

**Comment by absci** [comment]
Hi, due to the limitation of the SQL Server, alter the id column from INT to BIGINT with identity is not possible. One approach is to drop the primary key constraint, alter the column to BIGINT, then add the primary key. If there are any foreign key constraints that reference the PK, they also need to drop first and recreate later. It would be great if you decide to work on this. I haven't spent much time on fix this issue, so I'm not sure if there are any obstacles ahead.

**Comment by NBajanca** [comment]
Hi, thank you both for the work so far. 

To add to this issue, [django-oauth-toolkit](https://github.com/jazzband/django-oauth-toolkit/blob/master/CHANGELOG.md#100-2017-06-07) (over 2k stars on GitHub) introduces in v1.0.0 a migration that causes this issue: 

> Changed id field on Application, AccessToken, RefreshToken and Grant to BigAutoField (bigint/bigserial)

This type of migration certainly happens with other packages because other backends don't have this limitation.

**Comment by sg3-141-592** [comment]
> This type of migration certainly happens with other packages because other backends don't have this limitation.

Yes, the same issue happens when working with [Django-Tables2](https://github.com/jieter/django-tables2). To use MSSQL with it I've been using a fork from here [django-pyodbc-azure - Implement altering Autofield #189](https://github.com/michiya/django-pyodbc-azure/pull/189) which never got merged into the django-pyodbc-azure/django-mssql-backend trunk.

**Comment by jmah8** [comment]
Closing this issue as PR #128 fixes this and has been merged into dev.
